### PR TITLE
3.0.0 release

### PR DESCRIPTION
**Pull request by yowmamasita**
I can't find the file that configures the Sphinx url to `docs3alpha`, but I'm changing it to `docs3`.
Or, another suggestion: use the `docs` url instead and transfer Ferris 2 to `docs2`.

For those who are viewing this and wondering what's changed, when @jonparrott released Ferris 3 it is (for all intents and purposes) already complete. But since Google Cloud Endpoints was still in beta at that time, it needed the time to test the waters first and so was released in alpha.

### CODE REVIEW

**Comment by jonparrott** [comment]
Thanks for this - I will review it before EOD tomorrow.

**Comment by jonparrott** [comment]
Can you add another commit to this to rebuilt the docs?

**Comment by yowmamasita** [comment]
@jonparrott should I remove the gitignore reference to `docs/_build` or just test if the doc build works?

**Comment by jonparrott** [comment]
Oh, fair enough. Hmm. Just make sure the doc build works. We probably need to figure out a real release process here at some point.

**Comment by jonparrott** [comment]
This LGTM, but I'm going to hold off on merging until I have some time to perform the actual release.

**Pull request closed without merging**
