### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by yowmamasita**
In Travis, under the project's settings, create environment variable `APPENGINE_SDK_VERSION` (I set it to latest: `1.9.33`)

### CODE REVIEW

**Comment by jonparrott** [comment]
We can do better. Why not install https://github.com/GoogleCloudPlatform/python-repo-tools and use gcprepotools download-appengine-sdk ?

**Comment by yowmamasita** [comment]
@jonparrott I didn't know about that until now. Cool! :+1: Let me check this out

**Comment by jonparrott** [comment]
I just wrote it last week. :)

**Comment by jonparrott** [comment]
I've done this.

**Pull request closed without merging**
